/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UX_UI;

import dao.CommentDAO;
import dao.readerDao;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import library.Auth;
import library.MsgBox;
import library.XImage;
import model.Comment;
import model.Reader;
import model.Sach;

/**
 *
 * @author phamhuy
 */
public class JDialogEditBinhLuan extends javax.swing.JDialog {

    Sach sachh = new Sach();
    Comment cm = new Comment();
    CommentDAO dao = new CommentDAO();
    readerDao daoreader = new readerDao();
    int sao;

    /**
     * Creates new form JDialogEditBinhLuan
     */
    public JDialogEditBinhLuan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDialogEditBinhLuan(javax.swing.JDialog parent, boolean modal, Comment comment, Sach sach) {
        super(parent, modal);
        initComponents();
        cm = comment;
        sao = cm.getSao();
        sachh = sach;
//        System.out.println(cm.getIdReader() + cm.getContent());
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUserIMG = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUserComment = new javax.swing.JTextArea();
        btnUpload = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnUserStar1 = new javax.swing.JButton();
        btnUserStar2 = new javax.swing.JButton();
        btnUserStar3 = new javax.swing.JButton();
        btnUserStar4 = new javax.swing.JButton();
        btnUserStar5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblUserIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github50.png"))); // NOI18N

        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("HuyDZ");

        txtUserComment.setColumns(20);
        txtUserComment.setLineWrap(true);
        txtUserComment.setRows(5);
        txtUserComment.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtUserComment);

        btnUpload.setText("Xác Nhận");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnCancel.setText("Huỷ");

        btnUserStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar1.setText("1");
        btnUserStar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar1ActionPerformed(evt);
            }
        });

        btnUserStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar2.setText("2");
        btnUserStar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar2ActionPerformed(evt);
            }
        });

        btnUserStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar3.setText("3");
        btnUserStar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar3ActionPerformed(evt);
            }
        });

        btnUserStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar4.setText("4");
        btnUserStar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar4ActionPerformed(evt);
            }
        });

        btnUserStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png"))); // NOI18N
        btnUserStar5.setText("5");
        btnUserStar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblUserIMG)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUserStar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserStar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserStar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserStar4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUserStar5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpload)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblUserIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(btnUpload)
                    .addComponent(btnCancel)
                    .addComponent(btnUserStar1)
                    .addComponent(btnUserStar2)
                    .addComponent(btnUserStar3)
                    .addComponent(btnUserStar4)
                    .addComponent(btnUserStar5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Chỉnh sửa bình luận");

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backward.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(342, 342, 342))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserStar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar1ActionPerformed
        // TODO add your handling code here:
        sao = 1;
        setfromUserComment();
       
    }//GEN-LAST:event_btnUserStar1ActionPerformed

    private void btnUserStar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar2ActionPerformed
        // TODO add your handling code here:
        sao = 2;
        setfromUserComment();
    }//GEN-LAST:event_btnUserStar2ActionPerformed

    private void btnUserStar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar3ActionPerformed
        // TODO add your handling code here:
        sao = 3;
        setfromUserComment();
    }//GEN-LAST:event_btnUserStar3ActionPerformed

    private void btnUserStar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar4ActionPerformed
        // TODO add your handling code here:
        sao = 4;
        setfromUserComment();
    }//GEN-LAST:event_btnUserStar4ActionPerformed

    private void btnUserStar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStar5ActionPerformed
        // TODO add your handling code here:
        sao = 5;
        setfromUserComment();
    }//GEN-LAST:event_btnUserStar5ActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        openComment();
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEditBinhLuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEditBinhLuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEditBinhLuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEditBinhLuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEditBinhLuan dialog = new JDialogEditBinhLuan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnUserStar1;
    private javax.swing.JButton btnUserStar2;
    private javax.swing.JButton btnUserStar3;
    private javax.swing.JButton btnUserStar4;
    private javax.swing.JButton btnUserStar5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUserIMG;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextArea txtUserComment;
    // End of variables declaration//GEN-END:variables

    void init() {
        setLocationRelativeTo(null);
        loadfrom();
    }

    void loadfrom() {
        setfrom(cm, lblUserIMG, lblUserName, txtUserComment, btnUserStar1, btnUserStar2, btnUserStar3, btnUserStar4, btnUserStar5);
    }

    void setfrom(Comment cm, JLabel avatar, JLabel idreader, JTextArea noidung, JButton motsao, JButton haisao, JButton basao, JButton bonsao, JButton namsao) {
        noidung.setText(cm.getContent());
        cm.getSao();
        Reader rd = daoreader.selectByID(cm.getIdReader());
        if (rd.getAvatar() != null) {
            ImageIcon icon = XImage.read(rd.getAvatar());
            Image img = icon.getImage().getScaledInstance(avatar.getWidth(), avatar.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(img);
            avatar.setIcon(scaledIcon);
            avatar.setToolTipText(rd.getAvatar());
        };
        idreader.setText(rd.getHoTen());
        if (cm.getSao() != 0) {
            switch (cm.getSao()) {
                case 1 -> {
                    motsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    haisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                    basao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                    bonsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                    namsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                }
                case 2 -> {
                    motsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    haisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    basao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                    bonsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                    namsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                }
                case 3 -> {
                    motsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    haisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    basao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    bonsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                    namsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                }
                case 4 -> {
                    motsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    haisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    basao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    bonsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    namsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                }
                case 5 -> {
                    motsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    haisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    basao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    bonsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                    namsao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                }
            }
        }

    }

    Comment getFrom() {
        Comment comment = new Comment();
        comment.setIdDanhGia(cm.getIdDanhGia());
        comment.setIdReader(cm.getIdReader());
        comment.setIdSach(cm.getIdSach());
        comment.setSao(sao);
        comment.setContent(txtUserComment.getText());
        comment.setImages(null);
        comment.setVideos(null);
        comment.setEditable(true);
        comment.setEnable(true);

        return comment;
    }

    void update() {
        Comment cm = getFrom();
        try {
            dao.update(cm);
//            loadCommentBySach();
            MsgBox.alert(this, "Update thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Update thành công");
        }
    }

    void openComment() {
        this.dispose();
        new JDialogBinhLuan(this, true, sachh).setVisible(true);
    }

    void setfromUserComment() {
        Reader rd = daoreader.selectByID(Auth.user.getUserID());
        if (rd.getAvatar() != null) {
            ImageIcon icon = XImage.read(rd.getAvatar());
            Image img = icon.getImage().getScaledInstance(lblUserIMG.getWidth(), lblUserIMG.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(img);
            lblUserIMG.setIcon(scaledIcon);
            lblUserIMG.setToolTipText(rd.getAvatar());
        };
        lblUserName.setText(rd.getHoTen());
        switch (sao) {
            case 0 -> {
                btnUserStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
            }
            case 1 -> {
                btnUserStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
            }
            case 2 -> {
                btnUserStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
            }
            case 3 -> {
                btnUserStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
                btnUserStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
            }
            case 4 -> {
                btnUserStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty-small-star-16.png")));
            }
            case 5 -> {
                btnUserStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
                btnUserStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-star.png")));
            }
        }
    }

}
